import * as SQLite from 'expo-sqlite';
import type { Task,TaskDraft,TaskMemo,MemoInputType } from '../types';
import { uuid } from '../utils/date';

const dbPromise=SQLite.openDatabaseAsync('voice-work.db');
export async function initDatabase(){const db=await dbPromise;await db.execAsync(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',scheduled_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('PENDING','IN_PROGRESS','COMPLETED')),category TEXT NOT NULL,reminder_minutes INTEGER,notification_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task_memos(id TEXT PRIMARY KEY NOT NULL,task_id TEXT NOT NULL,content TEXT NOT NULL,input_type TEXT NOT NULL CHECK(input_type IN ('TEXT','VOICE')),created_at TEXT NOT NULL,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_tasks_scheduled ON tasks(scheduled_at);CREATE INDEX IF NOT EXISTS idx_memos_task ON task_memos(task_id,created_at);PRAGMA user_version=1;`)}
const mapTask=(r:any):Task=>({id:r.id,title:r.title,description:r.description,scheduledAt:r.scheduled_at,status:r.status,category:r.category,reminderMinutes:r.reminder_minutes,notificationId:r.notification_id,createdAt:r.created_at,updatedAt:r.updated_at});
export async function listTasks(){const db=await dbPromise;return (await db.getAllAsync<any>('SELECT * FROM tasks ORDER BY scheduled_at ASC')).map(mapTask)}
export async function getTask(id:string){const db=await dbPromise;const r=await db.getFirstAsync<any>('SELECT * FROM tasks WHERE id=?',id);return r?mapTask(r):null}
export async function createTask(d:TaskDraft){const db=await dbPromise;const id=uuid(),now=new Date().toISOString();await db.runAsync('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,d.title,d.description,d.scheduledAt,d.status,d.category,d.reminderMinutes,null,now,now);return (await getTask(id))!}
export async function updateTask(id:string,d:TaskDraft){const db=await dbPromise;await db.runAsync('UPDATE tasks SET title=?,description=?,scheduled_at=?,status=?,category=?,reminder_minutes=?,updated_at=? WHERE id=?',d.title,d.description,d.scheduledAt,d.status,d.category,d.reminderMinutes,new Date().toISOString(),id);return (await getTask(id))!}
export async function setNotificationId(id:string,value:string|null){const db=await dbPromise;await db.runAsync('UPDATE tasks SET notification_id=?,updated_at=? WHERE id=?',value,new Date().toISOString(),id)}
export async function deleteTaskRow(id:string){const db=await dbPromise;await db.runAsync('DELETE FROM tasks WHERE id=?',id)}
export async function listMemos(taskId:string){const db=await dbPromise;return db.getAllAsync<TaskMemo>('SELECT id,task_id as taskId,content,input_type as inputType,created_at as createdAt FROM task_memos WHERE task_id=? ORDER BY created_at ASC',taskId)}
export async function addMemo(taskId:string,content:string,inputType:MemoInputType){const db=await dbPromise;const memo={id:uuid(),taskId,content,inputType,createdAt:new Date().toISOString()};await db.runAsync('INSERT INTO task_memos VALUES(?,?,?,?,?)',memo.id,memo.taskId,memo.content,memo.inputType,memo.createdAt);return memo}
export async function exportData(){return {schemaVersion:1,exportedAt:new Date().toISOString(),tasks:await listTasks(),memos:await (await dbPromise).getAllAsync<TaskMemo>('SELECT id,task_id as taskId,content,input_type as inputType,created_at as createdAt FROM task_memos ORDER BY created_at')}}
export async function importData(data:any,mode:'merge'|'replace'){if(!data||data.schemaVersion!==1||!Array.isArray(data.tasks)||!Array.isArray(data.memos))throw new Error('지원하지 않는 백업 파일입니다.');for(const t of data.tasks){if(!t.id||!t.title||!t.scheduledAt||!['PENDING','IN_PROGRESS','COMPLETED'].includes(t.status))throw new Error('일정 데이터 형식이 올바르지 않습니다.')}const db=await dbPromise;await db.withTransactionAsync(async()=>{if(mode==='replace'){await db.runAsync('DELETE FROM task_memos');await db.runAsync('DELETE FROM tasks')}for(const t of data.tasks)await db.runAsync('INSERT OR REPLACE INTO tasks VALUES(?,?,?,?,?,?,?,?,?,?,?)',t.id,t.title,t.description??'',t.scheduledAt,t.status,t.category??'업무',t.reminderMinutes??null,null,t.createdAt??new Date().toISOString(),t.updatedAt??new Date().toISOString());for(const m of data.memos)if(m.id&&m.taskId&&m.content)await db.runAsync('INSERT OR REPLACE INTO task_memos VALUES(?,?,?,?,?)',m.id,m.taskId,m.content,m.inputType==='VOICE'?'VOICE':'TEXT',m.createdAt??new Date().toISOString())})}
