import * as SQLite from 'expo-sqlite';
import type {AppSettings,MemoInputType,NotificationMode,ReminderDraft,ReminderRepeat,ReminderRule,Task,TaskDraft,TaskMemo,TaskStatus} from '../types';
import {uuid} from '../utils/date';

type TaskRow={id:string;title:string;description:string;scheduled_at:string;status:TaskStatus;category:string;reminder_minutes:number|null;notification_id:string|null;repeat_start_offset:number|null;repeat_interval:number|null;repeat_count:number|null;repeat_until_completed:number;repeat_include_due:number;created_at:string;updated_at:string};
type ReminderRow={id:string;task_id:string;offset_minutes:number;mode:NotificationMode;notification_id:string|null};
type SettingsRow={default_mode:NotificationMode;default_offset_minutes:number;default_repeat_interval:number|null;default_repeat_count:number};
type Backup={schemaVersion:number;tasks:Task[];memos:TaskMemo[];settings?:AppSettings};

const dbPromise=SQLite.openDatabaseAsync('voice-work.db');
export const DEFAULT_SETTINGS:AppSettings={defaultMode:'normal',defaultOffsetMinutes:10,defaultRepeatInterval:null,defaultRepeatCount:1};

export async function initDatabase(){const db=await dbPromise;await db.execAsync(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',scheduled_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('PENDING','IN_PROGRESS','COMPLETED')),category TEXT NOT NULL,reminder_minutes INTEGER,notification_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task_memos(id TEXT PRIMARY KEY NOT NULL,task_id TEXT NOT NULL,content TEXT NOT NULL,input_type TEXT NOT NULL CHECK(input_type IN ('TEXT','VOICE')),created_at TEXT NOT NULL,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);`);const columns=await db.getAllAsync<{name:string}>('PRAGMA table_info(tasks)');const names=new Set(columns.map(c=>c.name));for(const [name,sql] of [['repeat_start_offset','INTEGER'],['repeat_interval','INTEGER'],['repeat_count','INTEGER'],['repeat_until_completed','INTEGER NOT NULL DEFAULT 0'],['repeat_include_due','INTEGER NOT NULL DEFAULT 0']] as const)if(!names.has(name))await db.execAsync(`ALTER TABLE tasks ADD COLUMN ${name} ${sql}`);await db.execAsync(`CREATE TABLE IF NOT EXISTS reminder_rules(id TEXT PRIMARY KEY NOT NULL,task_id TEXT NOT NULL,offset_minutes INTEGER NOT NULL,mode TEXT NOT NULL CHECK(mode IN ('normal','voice','alarm')),notification_id TEXT,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS app_settings(id INTEGER PRIMARY KEY CHECK(id=1),default_mode TEXT NOT NULL,default_offset_minutes INTEGER NOT NULL,default_repeat_interval INTEGER,default_repeat_count INTEGER NOT NULL);
INSERT OR IGNORE INTO app_settings VALUES(1,'normal',10,NULL,1);
INSERT INTO reminder_rules(id,task_id,offset_minutes,mode,notification_id) SELECT lower(hex(randomblob(16))),id,reminder_minutes,'normal',notification_id FROM tasks WHERE reminder_minutes IS NOT NULL AND NOT EXISTS(SELECT 1 FROM reminder_rules r WHERE r.task_id=tasks.id);
CREATE INDEX IF NOT EXISTS idx_tasks_scheduled ON tasks(scheduled_at);CREATE INDEX IF NOT EXISTS idx_memos_task ON task_memos(task_id,created_at);CREATE INDEX IF NOT EXISTS idx_reminders_task ON reminder_rules(task_id);PRAGMA user_version=2;`)}

const mapReminder=(r:ReminderRow):ReminderRule=>({id:r.id,taskId:r.task_id,offsetMinutes:r.offset_minutes,mode:r.mode,notificationId:r.notification_id});
const mapRepeat=(r:TaskRow):ReminderRepeat|null=>r.repeat_start_offset===null||r.repeat_interval===null?null:{startOffsetMinutes:r.repeat_start_offset,intervalMinutes:r.repeat_interval,repeatCount:r.repeat_count,untilCompleted:r.repeat_until_completed===1,includeDueTime:r.repeat_include_due===1};
async function hydrate(rows:TaskRow[]){const db=await dbPromise;const reminders=(await db.getAllAsync<ReminderRow>('SELECT * FROM reminder_rules ORDER BY offset_minutes DESC')).map(mapReminder);return rows.map(r=>({id:r.id,title:r.title,description:r.description,scheduledAt:r.scheduled_at,status:r.status,category:r.category,reminderMinutes:r.reminder_minutes,notificationId:r.notification_id,reminders:reminders.filter(x=>x.taskId===r.id),repeat:mapRepeat(r),createdAt:r.created_at,updatedAt:r.updated_at}));}
export async function listTasks(){const db=await dbPromise;return hydrate(await db.getAllAsync<TaskRow>('SELECT * FROM tasks ORDER BY scheduled_at ASC'))}
export async function getTask(id:string){const db=await dbPromise;const r=await db.getFirstAsync<TaskRow>('SELECT * FROM tasks WHERE id=?',id);return r?(await hydrate([r]))[0]:null}
async function replaceRules(taskId:string,rules:ReminderDraft[]){const db=await dbPromise;await db.runAsync('DELETE FROM reminder_rules WHERE task_id=?',taskId);for(const r of rules)await db.runAsync('INSERT INTO reminder_rules VALUES(?,?,?,?,NULL)',uuid(),taskId,r.offsetMinutes,r.mode)}
export async function createTask(d:TaskDraft){const db=await dbPromise;const id=uuid(),now=new Date().toISOString(),r=d.repeat;await db.withTransactionAsync(async()=>{await db.runAsync('INSERT INTO tasks(id,title,description,scheduled_at,status,category,reminder_minutes,notification_id,repeat_start_offset,repeat_interval,repeat_count,repeat_until_completed,repeat_include_due,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,d.title,d.description,d.scheduledAt,d.status,d.category,d.reminders[0]?.offsetMinutes??null,null,r?.startOffsetMinutes??null,r?.intervalMinutes??null,r?.repeatCount??null,r?.untilCompleted?1:0,r?.includeDueTime?1:0,now,now);await replaceRules(id,d.reminders)});return (await getTask(id))!}
export async function updateTask(id:string,d:TaskDraft){const db=await dbPromise,r=d.repeat;await db.withTransactionAsync(async()=>{await db.runAsync('UPDATE tasks SET title=?,description=?,scheduled_at=?,status=?,category=?,reminder_minutes=?,notification_id=NULL,repeat_start_offset=?,repeat_interval=?,repeat_count=?,repeat_until_completed=?,repeat_include_due=?,updated_at=? WHERE id=?',d.title,d.description,d.scheduledAt,d.status,d.category,d.reminders[0]?.offsetMinutes??null,r?.startOffsetMinutes??null,r?.intervalMinutes??null,r?.repeatCount??null,r?.untilCompleted?1:0,r?.includeDueTime?1:0,new Date().toISOString(),id);await replaceRules(id,d.reminders)});return (await getTask(id))!}
export async function setReminderNotificationId(ruleId:string,value:string|null){const db=await dbPromise;await db.runAsync('UPDATE reminder_rules SET notification_id=? WHERE id=?',value,ruleId)}
export async function deleteTaskRow(id:string){const db=await dbPromise;await db.runAsync('DELETE FROM tasks WHERE id=?',id)}
export async function listMemos(taskId:string){const db=await dbPromise;return db.getAllAsync<TaskMemo>('SELECT id,task_id as taskId,content,input_type as inputType,created_at as createdAt FROM task_memos WHERE task_id=? ORDER BY created_at ASC',taskId)}
export async function addMemo(taskId:string,content:string,inputType:MemoInputType){const db=await dbPromise;const memo={id:uuid(),taskId,content,inputType,createdAt:new Date().toISOString()};await db.runAsync('INSERT INTO task_memos VALUES(?,?,?,?,?)',memo.id,memo.taskId,memo.content,memo.inputType,memo.createdAt);return memo}
export async function getSettings(){const db=await dbPromise;const r=await db.getFirstAsync<SettingsRow>('SELECT default_mode,default_offset_minutes,default_repeat_interval,default_repeat_count FROM app_settings WHERE id=1');return r?{defaultMode:r.default_mode,defaultOffsetMinutes:r.default_offset_minutes,defaultRepeatInterval:r.default_repeat_interval,defaultRepeatCount:r.default_repeat_count}:DEFAULT_SETTINGS}
export async function saveSettings(s:AppSettings){const db=await dbPromise;await db.runAsync('INSERT OR REPLACE INTO app_settings VALUES(1,?,?,?,?)',s.defaultMode,s.defaultOffsetMinutes,s.defaultRepeatInterval,s.defaultRepeatCount)}
export async function exportData(){return {schemaVersion:2,exportedAt:new Date().toISOString(),tasks:await listTasks(),memos:await (await dbPromise).getAllAsync<TaskMemo>('SELECT id,task_id as taskId,content,input_type as inputType,created_at as createdAt FROM task_memos ORDER BY created_at'),settings:await getSettings()}}
export async function importData(raw:unknown,mode:'merge'|'replace'){if(!raw||typeof raw!=='object')throw new Error('지원하지 않는 백업 파일입니다.');const data=raw as Partial<Backup>;if(![1,2].includes(data.schemaVersion??0)||!Array.isArray(data.tasks)||!Array.isArray(data.memos))throw new Error('지원하지 않는 백업 파일입니다.');const tasks=data.tasks,memos=data.memos;const db=await dbPromise;await db.withTransactionAsync(async()=>{if(mode==='replace'){await db.runAsync('DELETE FROM task_memos');await db.runAsync('DELETE FROM tasks')}for(const t of tasks){if(!t.id||!t.title||!t.scheduledAt)throw new Error('일정 데이터 형식이 올바르지 않습니다.');const reminders=t.reminders?.map(x=>({offsetMinutes:x.offsetMinutes,mode:x.mode}))??(t.reminderMinutes===null?[]:[{offsetMinutes:t.reminderMinutes??10,mode:'normal' as const}]);const draft:TaskDraft={title:t.title,description:t.description??'',scheduledAt:t.scheduledAt,status:t.status,category:t.category??'업무',reminderMinutes:reminders[0]?.offsetMinutes??null,reminders,repeat:t.repeat??null};await db.runAsync('DELETE FROM tasks WHERE id=?',t.id);const r=draft.repeat,now=new Date().toISOString();await db.runAsync('INSERT INTO tasks(id,title,description,scheduled_at,status,category,reminder_minutes,notification_id,repeat_start_offset,repeat_interval,repeat_count,repeat_until_completed,repeat_include_due,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',t.id,draft.title,draft.description,draft.scheduledAt,draft.status,draft.category,draft.reminderMinutes,null,r?.startOffsetMinutes??null,r?.intervalMinutes??null,r?.repeatCount??null,r?.untilCompleted?1:0,r?.includeDueTime?1:0,t.createdAt??now,t.updatedAt??now);await replaceRules(t.id,reminders)}for(const m of memos)if(m.id&&m.taskId&&m.content)await db.runAsync('INSERT OR REPLACE INTO task_memos VALUES(?,?,?,?,?)',m.id,m.taskId,m.content,m.inputType==='VOICE'?'VOICE':'TEXT',m.createdAt??new Date().toISOString());if(data.settings)await saveSettings(data.settings)})}
